### ISSUE TITLE
unpickling stack underflow

### ISSUE THREAD

**Issue by ZhangYu1ing** [pigtigger/CenterPoint-with-Colab#1]
Hi, I am also trying to implement CenterPoint on Colab. I met the pickle.UnpicklingError when I tried to run demo.py which is shown as below. Did you meet the same problem? May I ask the possible way to solve it? Thanks in advance.

-------------Error----------------
2021-03-14 16:24:04.932917: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
No Tensorflow
Deformable Convolution not built!
Use HM Bias:  -2.19
10
Traceback (most recent call last):
  File "demo.py", line 130, in <module>
    main()
  File "demo.py", line 71, in main
    checkpoint = load_checkpoint(model, 'work_dirs/centerpoint_pillar_512_demo/latest.pth', map_location="cpu")
  File "/content/gdrive/My Drive/Colab Notebooks/CenterPoint-colab/CenterPoint/det3d/torchie/trainer/checkpoint.py", line 157, in load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow

**Comment by pigtigger** [comment]
Did you download the model (By default, centerpoint_pillar_512) and put it in work_dirs/centerpoint_pillar_512_demo🤔？

**Comment by ZhangYu1ing** [comment]
<img width="693" alt="Screen Shot 2021-03-14 at 5 57 34 PM" src="https://user-images.githubusercontent.com/37301722/111076940-c2c97e80-84ee-11eb-85d0-b9a6a20cb64d.png">
Yes, I did. Did you modify the demo.py file? For example, replace the 'cpu' to 'cuda'?

**Comment by pigtigger** [comment]
i didn't modify any code

**Comment by ZhangYu1ing** [comment]
Yes, you are right! I redownloaded the lastest.pth file, and it worked! Thanks a lot~😬

**Comment by pigtigger** [comment]
:)
